### ISSUE TITLE
Write tests for every feature on the SRS

### ISSUE THREAD

**Issue by rodomvp** [rodomvp/KennelApp#77]
Necessary for the STD document (using IEEE 829 standard as much as possible)

This is going to be a massive undertaking that should probably be started ASAP. Might be valuable for one person to focus exclusively on writing tests for backlogged, testless features that we have currently. IDK but this is going to be a monster task.

**Comment by rgulle4** [comment]
Closing this, just to make the issues list one item shorter. Tests are definitely on everyone's mind, and is being worked on along with other stuff.
