### ISSUE TITLE
Patient pictures

### ISSUE THREAD

**Issue by eribandogros** [rodomvp/KennelApp#81]
Need a way to add in a picture to a patient profile.

**Comment by rgulle4** [comment]
I think Austin's on this, and afaik he'll use that Carrierwave stuff.

**Comment by rgulle4** [comment]
This was closed in one ore more of these commits:

- 8b70c10 Add image upload... a big ole rebase... (Vincent Rodomista)
- d501434 Everyone pls do `figaro install`, and get sekrets (rgulle4)
- 2648907 Merge branch 'master' of github.com:rodomvp/RVDE-LSU-3380 (Vincent Rodomista)
- e93ead2 fix new images (Vincent Rodomista)
- 8dc9f7b Merge remote-tracking branch 'origin/master' into vincent-messed-up (rgulle4)
