### ISSUE TITLE
Add Patient button in `owners/1` view isn't always clickable

### ISSUE THREAD

**Issue by rgulle4** [rodomvp/KennelApp#82]
Seems like it's clickable only when the window is huge. At normal sizes, it doesn't respond, not even to a mouseover.

![image](https://cloud.githubusercontent.com/assets/12738315/14651353/3e9b65b6-0635-11e6-82b5-b3315135c3ba.png)

**Comment by eribandogros** [comment]
I think I fixed this with my new pull request #83

**Comment by rodomvp** [comment]
fixed thanks to @eribandogros
