### ISSUE TITLE
Patients view doesn't show all patients, and there's no pagination

### ISSUE THREAD

**Issue by rgulle4** [rodomvp/KennelApp#86]
The Patients view doesn't show all the patients.

PROOF: 

1. Go to <https://kennelapp.herokuapp.com/all_patients>
2. Scan the list or use ur browser's search, and you won't find **Cornelius** on the list.
3. Using the seach box (`/` keyboard shortcut), search for **Cornelius**. He's definitely in the db, but just isn't showing up in the list.

PLS FIX:

It needs to either

- show all the patients in one long list (it currently doesn't).
- or needs to be paginated.

**Comment by eribandogros** [comment]
fixed with commit e720ed241955481af01356086aa7b7c587d26948
pagination works now and Cornelius is showing up

**Comment by rgulle4** [comment]
I thought this was fixed? Or was that a dream?

**Comment by rodomvp** [comment]
i think this is fixed..

**Comment by rgulle4** [comment]
It wasn't fixed.
