### ISSUE TITLE
Create patient partial with relevant information

### ISSUE THREAD

**Issue by rodomvp** [rodomvp/KennelApp#88]
This is the number one issue blocking the rest of the ward view design. Must be knocked out before this weekend begins.

**Comment by rgulle4** [comment]
_I_ probably won't be able to do this (not tonight at least, bc I'm on ward view ish).

FWIW, we have this in the SDD. Not sure how close we are to this in our best imagination...

![image](https://cloud.githubusercontent.com/assets/12738315/14727119/be9eca0a-07ed-11e6-9880-be2baff4f5f5.png)

**Comment by rgulle4** [comment]
We're slowly, but surely (maybe haphazardly) chipping away at this...

As of Saturday night:

![image](https://cloud.githubusercontent.com/assets/12738315/14765799/1ddad65a-09b8-11e6-8c69-1909b11e0571.png)

**Comment by rgulle4** [comment]
Sorry, I'm behind on this. Doing this tomorrow though, I hope.

**Comment by rodomvp** [comment]
meh
