### ISSUE TITLE
Checked out patient shouldn't be sorted at the top of index

### ISSUE THREAD

**Issue by eribandogros** [rodomvp/KennelApp#90]
When you check out a patient, that patient floats to the top of the patients list in the /patients page.
Instead this patient should be with the rest of the patients that aren't checked below the checked in patients.

**Comment by rgulle4** [comment]
a pic of what OP looks like...

![image](https://cloud.githubusercontent.com/assets/12738315/14776114/c0ab39ca-0a89-11e6-92c0-376f6724aca1.png)

**Comment by rgulle4** [comment]
@kjhoupy has this fixed on his local; just hasn't pushed it yet.

**Comment by rgulle4** [comment]
Closed in 01590448779ea039aca07b77b0786957ccfa2baa
