### ISSUE TITLE
Deleting a checked in patient

### ISSUE THREAD

**Issue by eribandogros** [rodomvp/KennelApp#91]
When you delete a checked in patient, errors pop up in the ward view and runn show for that patient.
I suspect it has to do with the `occupied?` variable not being reset when a stay is destroyed.

**Comment by rgulle4** [comment]
NB to whoever deals with this... 42a4a4e78526d79d0c7c7e5d1c32d414cc4e7b42

**Comment by eribandogros** [comment]
This is the error I'm getting
![Error](https://cloud.githubusercontent.com/assets/14114157/14774815/b2f3624e-0a7f-11e6-9486-1244f0f4402f.png)
