### ISSUE TITLE
Ward view layout bug

### ISSUE THREAD

**Issue by eribandogros** [rodomvp/KennelApp#92]
I think this is a new problem, might be related to when I messed with some of the css.

![Ward View](https://cloud.githubusercontent.com/assets/14114157/14774878/6eeb059c-0a80-11e6-953c-a6580c15329b.png)

**Comment by rgulle4** [comment]
it's the height of those thumbnails. My n00b eyes see two ways to fix this:

- Make those thumbnail heights smaller, so that they don't expand the panels.. OR...
- For **VACANT** `_runn`s, put a spacer gif where the thumbnail would be, and make it the same height as the thumbnails.
