### ISSUE TITLE
Allow user to edit Ward info

### ISSUE THREAD

**Issue by kjhoupy** [rodomvp/KennelApp#93]
Right now only the admin can do this.

**Comment by rgulle4** [comment]
Just move one line... and make other changes to make sure the page doesn't look confusing with a "Edit" just sitting there.

```ruby
<% if current_user.admin? %>
  <%= link_to 'Edit', edit_ward_path(@ward) %> |  ## <-- move this out of the `if`
  <%= link_to 'Back', wards_path %>
<% end %>
```

https://github.com/rodomvp/KennelApp/blob/master/app/views/wards/show.html.erb#L18

**Comment by eribandogros** [comment]
I'm working on this right now
